import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from "next";

const inter = Inter({ subsets: ['latin'] })

export const metadata:Metadata= {
    title: ' about App',
    // description: 'Generated by Hayat',
  }

function Head() {
  return (
    <div>head</div>
  )
}

export default Head