import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'


const inter = Inter({ subsets: ['latin'] })

export const metadata:Metadata = {
  title: 'My next App',
  description: 'Generated by Hayat',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1> Nav bar </h1>
        {children}
      </body>
    </html>
  )
}
